zsync: fix missing include for strings.h
http.c:128:13: error: implicitly declaring library function 'strcasecmp' with type 'int (const char *, const char *)' [-Werror,-Wimplicit-function-declaration]
        if (strcasecmp(buf, "Location"))
            ^
http.c:128:13: note: include the header <strings.h> or explicitly provide a declaration for 'strcasecmp'
http.c:916:17: error: implicitly declaring library function 'strncasecmp' with type 'int (const char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
            && !strncasecmp(p, "multipart/byteranges", 20)) {
                ^
http.c:916:17: note: include the header <strings.h> or explicitly provide a declaration for 'strncasecmp'
2 errors generated.