Update lftp to version 4.5.0
Fix bug #27 "lftp on OS X 10.7 Lion does not support ftp protocol".
Remove patch inflateReset.diff for OS X 10.6.

Unfortunately 4.5.0 breaks on Mavericks and Mountain Lion:

Undefined symbols for architecture x86_64:
  "xarray_m<char>::dispose(char*)", referenced from:
      vtable for xarray_m<char> in complete.o
  "operator delete(void*)", referenced from:
      Ref<ArgV>::~Ref() in lftp.o
      AcceptTermFD::~AcceptTermFD() in lftp.o
      ReadlineFeeder::~ReadlineFeeder() in lftp.o
      non-virtual thunk to ReadlineFeeder::~ReadlineFeeder() in lftp.o
      CmdFeeder::~CmdFeeder() in lftp.o
      SendTermFD::~SendTermFD() in lftp.o
      Ref<Error>::~Ref() in lftp.o
      ...
  "operator new(unsigned long)", referenced from:
      cmd_attach(CmdExec*) in lftp.o
      _main in lftp.o
      lftp_rl_getc(__sFILE*) in complete.o
      lftp_completion(char const*, int, int) in complete.o
      _completion_display_list in complete.o
      cmd_completion_type(char const*, int) in complete.o
  "___cxa_pure_virtual", referenced from:
      vtable for CmdFeeder in lftp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lftp] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [build] Error 2

Signed-off-by: Rudá Moura <ruda.moura@gmail.com>
Signed-off-by: Ruda Moura <ruda@vm-snowleopard.local>